baseURL = 'https://shores.site/'
languageCode = 'en-us'
theme = "ananke"
title = 'shores'
DefaultContentLanguage = "en" 
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
SectionPagesMenu = "main" 
enableRobotsTXT = true 
googleAnalytics = "" 

[params]
facebook = ""
favicon = ""
github = "https://github.com/cedcn"
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = "https://twitter.com/shaojinjun"
youtube = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
description = "A little bit"
featured_image = "/images/pexels-maksim-goncharenok-4663822.jpg"
